Repository xsky-fe/wizard-ui, pull requests merged in 2019-08, with the labels that each got.

#37 refactor: Min dist js file
  .editorconfig
  .gitignore
  README.md
  package.json
  prettier.config.js
  src/components/Badge/index.test.tsx
  src/components/Badge/index.tsx
  src/components/DropdownButton/index.tsx
  src/components/Icon/index.test.tsx
  src/components/Icon/index.tsx
  src/components/Loader/index.test.tsx
  src/components/Loader/index.tsx
  src/components/Modal/index.tsx
  src/components/Navigation/index.tsx
  src/components/RangePicker/index.test.tsx
  src/components/RangePicker/index.tsx
  src/components/Steps/index.tsx
  src/components/SubMenu/index.tsx
  src/components/Switch/index.tsx
  src/components/Tabs/index.test.tsx
  src/components/Tabs/index.tsx
  src/components/TimePicker/index.tsx
  src/components/Tooltip/index.test.tsx
  src/components/Tooltip/index.tsx
  src/components/Tree/index.tsx
  src/components/UsageBar/index.test.tsx
  src/components/UsageBar/index.tsx
  src/components/index.tsx
  src/interface.tsx
  tsconfig.json
  webpack.config.js
Labels: enhancement

#38 refactor: Netlify site
  README.md
  netlify.toml
Labels: enhancement

#39 Feat/well
  .gitignore
  docs/.gitignore
  docs/content/components/well.mdx
  package.json
  src/components/index.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#40 feat: Mdx add author sub title
  docs/.prettierrc
  docs/content/components/badge.mdx
  docs/content/components/range-picker.mdx
  docs/content/components/well.mdx
  docs/src/Layout/index.js
  docs/src/components/GitHubIcon.js
  docs/src/components/Header/index.js
  docs/src/components/Header/style.scss
  docs/src/components/IssueIcon.js
  docs/src/components/seo.js
  docs/src/examples/index.js
  docs/src/pages/404.js
  docs/src/pages/index.js
  docs/src/templates/components-post.js
  docs/src/templates/default.js
  docs/src/utils/get-colors.js
  docs/src/utils/invert-color.js
  docs/src/utils/prop-type-parse.js
Labels: 1-Review, 4-Approved

#44 feat: Support css module.
  .storybook/webpack.config.js
  package.json
  src/global.d.ts
  webpack.config.js
Labels: 1-Review, 2-Change, 3-Changed

#45 refactor: Remove react SFC
  src/components/Badge/index.tsx
  src/components/DropdownButton/index.tsx
  src/components/Icon/index.tsx
  src/components/Loader/index.tsx
  src/components/Steps/index.tsx
  src/components/SubMenu/index.tsx
  src/components/Tabs/index.tsx
  src/components/TimePicker/index.tsx
  src/components/Tree/index.tsx
  src/components/UsageBar/index.tsx
Labels: 1-Review, 4-Approved

#48 refactor: Fix rc-tree versions
  docs/package.json
  package.json
Labels: 1-Review, 4-Approved

#47 feat: Add Dropdown component.
  docs/content/components/dropdown.mdx
  src/components/Dropdown/index.test.tsx
  src/components/Dropdown/index.tsx
  src/components/index.tsx
  src/interface.tsx
  stories/Dropdown.stories.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#53 feat: Add Navbar.
  docs/content/components/navbar.mdx
  src/components/index.tsx
Labels: 1-Review, 4-Approved

#55 fix: Component in docs ignore error
  docs/gatsby-config.js
  docs/package.json
  docs/src/templates/components-post.js
  docs/src/templates/default.js
  docs/yarn.lock
Labels: 1-Review, 4-Approved

#54 fix: Rename well component.
  docs/content/components/well.mdx
Labels: 1-Review, 4-Approved

#50 feat: Breadcrumb.
  docs/content/components/breadcrumb.mdx
Labels: 1-Review, 4-Approved

#46 Feat: Panel and panel group.
  docs/content/components/panel.mdx
  docs/content/components/panelgroup.mdx
  docs/src/Layout/bootstrap-custom.scss
  docs/src/Layout/variables.scss
  src/components/Panel/README.md
  src/components/Panel/index.scss
  src/components/Panel/index.test.tsx
  src/components/Panel/index.tsx
  src/components/index.tsx
  src/interface.tsx
  src/style/bootstrap-custom.scss
  src/style/variables.scss
Labels: 1-Review, 3-Changed, 4-Approved

#57 feat: Add nav.
  docs/content/components/menu-item.mdx
  docs/content/components/nav-dropdown.mdx
  docs/content/components/nav-item.mdx
  docs/content/components/nav.mdx
Labels: 1-Review, 4-Approved

#49 feat: DatePicker
  docs/content/components/date-picker.mdx
  docs/package.json
  docs/src/Layout/bootstrap-custom.scss
  docs/src/components/SideNav/index.js
  src/components/DatePicker/__snapshots__/index.test.tsx.snap
  src/components/DatePicker/index.test.tsx
  src/components/DatePicker/index.tsx
  src/components/DatePicker/style.scss
  src/components/TimePicker/index.tsx
  src/components/index.tsx
  src/interface.tsx
  src/style/bootstrap-custom.scss
  stories/DatePicker.stories.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#51 Feat: Add Font specification
  docs/content/layout/font.mdx
  docs/src/Layout/bootstrap-custom.scss
  docs/src/Layout/variables.scss
  src/style/bootstrap-custom.scss
  src/style/variables.scss
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#52 Feat: add alert
  docs/content/components/Alert.mdx
  src/components/Alert/index.test.tsx
  src/components/Alert/index.tsx
  src/components/Alert/style.scss
  src/components/DatePicker/index.tsx
  src/components/Dropdown/index.test.tsx
  src/components/Dropdown/index.tsx
  src/components/Panel/index.tsx
  src/components/index.tsx
  src/interface.tsx
  stories/Alert.stories.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#58 feat: Add grid.
  docs/content/components/clearfix.mdx
  docs/content/components/grid.mdx
  docs/src/components/Playground/style.scss
  src/components/Tree/index.tsx
  src/components/index.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#59 feat: VirtualList
  .storybook/style.scss
  docs/content/components/virtual-list.mdx
  docs/src/components/Playground/index.js
  docs/src/components/Playground/style.scss
  docs/src/utils/getMockDatas.js
  src/components/VirtualList/__snapshots__/index.test.tsx.snap
  src/components/VirtualList/index.test.tsx
  src/components/VirtualList/index.tsx
  src/components/VirtualList/style.scss
  src/components/index.tsx
  src/interface.tsx
  stories/VirtualList.stories.tsx
  stories/demos/AsyncVirtualList.tsx
  stories/utils/getMockDatas.ts
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#56 feat: Docs support search
  docs/gatsby-config.js
  docs/package.json
  docs/src/components/HeaderSearch.js
  docs/src/components/Search/index.js
  docs/src/components/Search/style.scss
  docs/src/components/TopBar/index.js
  docs/yarn.lock
Labels: 1-Review, 4-Approved

#62 feat: Add test and storybook for SubMenu.
  src/components/SubMenu/index.test.tsx
  src/components/SubMenu/index.tsx
  stories/SubMenu.stories.tsx
Labels: 1-Review, 4-Approved

#63 feat: Add DropdownButton storybook and test.
  src/components/DropdownButton/index.test.tsx
  src/components/DropdownButton/index.tsx
  src/interface.tsx
  stories/DropdownButton.stories.tsx
Labels: 1-Review, 4-Approved

#64 feat: Add InputDropdown.
  .storybook/webpack.config.js
  docs/content/components/input-dropdown.mdx
  docs/gatsby-config.js
  src/components/InputDropdown/index.test.tsx
  src/components/InputDropdown/index.tsx
  src/components/index.tsx
  src/interface.tsx
  stories/InputDropdown.stories.tsx
  webpack.config.js
Labels: 1-Review, 3-Changed, 4-Approved
