Repository xsky-fe/wizard-ui, pull requests merged in 2019-09, with the labels that each got.

#65 feat: VirtualSelectBox
  .storybook/config.ts
  docs/content/components/virtual-select-box.mdx
  src/components/DropdownButton/index.test.tsx
  src/components/DropdownButton/index.tsx
  src/components/Icon/style.scss
  src/components/SubMenu/index.test.tsx
  src/components/VirtualList/index.test.tsx
  src/components/VirtualList/index.tsx
  src/components/VirtualSelectBox/index.test.tsx
  src/components/VirtualSelectBox/index.tsx
  src/components/VirtualSelectBox/style.scss
  src/components/index.tsx
  src/interface.tsx
  src/utils/__tests__/elastic-query.test.ts
  src/utils/elastic-query.ts
  src/utils/get-mock-datas.ts
  src/utils/index.ts
  src/utils/sleep.ts
  stories/VirtualSelectBox.stories.tsx
  stories/demos/AsyncVirtualList.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved, good first issue

#68 feat: SEO sitemap
  docs/gatsby-config.js
  docs/package.json
  docs/yarn.lock
Labels: 1-Review, 4-Approved

#70 fix: Panel add class name
  docs/content/components/panel.mdx
  src/components/Panel/index.tsx
  src/interface.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#66 refactor: Modal props hideFooter
  docs/content/components/modal.mdx
  jest.config.js
  src/components/Modal/index.test.tsx
  src/components/Modal/index.tsx
  src/interface.tsx
Labels: 1-Review, 4-Approved

#71 refactor: Compare with react-bootstrap
  .release-it.json
  docs/package.json
  docs/yarn.lock
  package.json
  src/components/Dropdown/index.tsx
  src/components/Icon/__snapshots__/index.test.tsx.snap
  src/components/Icon/index.tsx
  src/components/Icon/style.scss
  src/components/Panel/index.tsx
  src/components/Tabs/index.tsx
  src/components/index.tsx
  src/global.d.ts
  src/interface.tsx
Labels: 1-Review, 4-Approved

#83 refactor: Update docs code
  .github/workflows/main.yml
  .gitignore
  ISSUE.md
  README.md
  docs/.gitignore
  docs/content/components/alert.mdx
  docs/content/components/badge.mdx
  docs/content/components/date-picker.mdx
  docs/content/components/dropdown-button.mdx
  docs/content/components/dropdown.mdx
  docs/content/components/grid.mdx
  docs/content/components/icon.mdx
  docs/content/components/input-dropdown.mdx
  docs/content/components/loader.mdx
  docs/content/components/modal.mdx
  docs/content/components/navigation.mdx
  docs/content/components/panelgroup.mdx
  docs/content/components/range-picker.mdx
  docs/content/components/steps.mdx
  docs/content/components/sub-menu.mdx
  docs/content/components/switch.mdx
  docs/content/components/tab.mdx
  docs/content/components/time-picker.mdx
  docs/content/components/tooltip.mdx
  docs/content/components/tree.mdx
  docs/content/components/usage-bar.mdx
  docs/content/components/virtual-list.mdx
  docs/content/components/virtual-select-box.mdx
  docs/content/get-started/introduction.mdx
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/package.json
  docs/src/Layout/bootstrap-custom.scss
  docs/src/Layout/index.js
  docs/src/Layout/style.scss
  docs/src/components/Header/index.js
  docs/src/components/Home/index.js
  docs/src/components/Playground/index.js
  docs/src/components/PropTable/index.js
  docs/src/components/Search/index.js
  docs/src/components/Search/style.scss
  docs/src/components/SideNav/Component.js
  docs/src/components/SideNav/Layout.js
  docs/src/components/SideNav/NavSection.js
  docs/src/components/SideNav/index.js
  docs/src/components/SideNav/style.scss
  docs/src/components/TopBar/index.js
  docs/src/components/TopBar/style.scss
  docs/src/templates/components-post.js
  docs/src/utils/hooks/get-window-width.js
  docs/yarn.lock
  src/components/Modal/index.tsx
  src/components/RangePicker/style.scss
  src/components/VirtualSelectBox/style.scss
  src/components/index.tsx
  yarn.lock
Labels: 1-Review, 4-Approved

#73 Feat/notification list
  .github/workflows/main.yml
  docs/content/components/notification-notification.mdx
  docs/content/components/notification.mdx
  docs/package.json
  docs/src/components/IssueIcon.js
  docs/src/components/TopBar/index.js
  docs/src/components/TopBar/style.scss
  docs/yarn.lock
  package.json
  src/components/Icon/index.tsx
  src/components/InputDropdown/index.test.tsx
  src/components/InputDropdown/index.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/NotificationList.tsx
  src/components/Notification/index.test.tsx
  src/components/Notification/index.tsx
  src/components/Notification/style.scss
  src/components/Panel/index.tsx
  src/components/VirtualList/index.tsx
  src/components/VirtualSelectBox/index.test.tsx
  src/components/VirtualSelectBox/index.tsx
  src/components/index.tsx
  src/global.d.ts
  src/hocs/intervalHoc.tsx
  src/interface.tsx
  stories/NotificationList.stories.tsx
  tsconfig.json
  yarn.lock
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#84 Fix generics error in tsx.
  src/components/VirtualList/index.tsx
  src/components/VirtualSelectBox/index.test.tsx
  src/components/VirtualSelectBox/index.tsx
  stories/VirtualSelectBox.stories.tsx
Labels: 1-Review, 4-Approved

#75 feat: VirtualSelectBox multi select
  docs/content/components/virtual-select-box.mdx
  src/components/VirtualSelectBox/SelectCheckItem.tsx
  src/components/VirtualSelectBox/index.tsx
  src/components/VirtualSelectBox/style.scss
  src/interface.tsx
  stories/VirtualSelectBox.stories.tsx
Labels: 1-Review, 4-Approved

#82 improve: remove init "x" in alert
  src/components/Alert/index.test.tsx
  src/components/Alert/index.tsx
Labels: 1-Review, 4-Approved

#81 feat: Add list group doc.
  docs/content/components/list-group.mdx
Labels: 1-Review

#72 Fix/steps
  docs/content/components/steps.mdx
  src/components/Steps/index.tsx
  src/interface.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved

#88 fix: Types define
  .gitignore
  package.json
  tsconfig.json
Labels: 1-Review, 4-Approved

#85 feat: Test debug platform in development
  docs/content/get-started/introduction.mdx
  package.json
Labels: 1-Review, 4-Approved

#89 feat: Support dark mode
  docs/content/components/virtual-list.mdx
  docs/src/Layout/index.js
  docs/src/Layout/style.scss
  docs/src/Layout/theme.scss
  docs/src/components/Header/style.scss
  docs/src/components/Playground/style.scss
  docs/src/components/SideNav/style.scss
  docs/src/components/Toc/style.scss
  docs/src/components/TopBar/index.js
  docs/src/components/TopBar/style.scss
  stories/NotificationList.stories.tsx
Labels: 1-Review, 2-Change, 3-Changed, 4-Approved
