Repository xsky-fe/wizard-ui, pull requests merged in 2023-08, with the labels that each got.

#278 fix: [XEOS-9576] change switch disabled opacity
  src/components/Switch/index.tsx
Labels: bug

#276 fix: ui style
  src/components/Badge/style.scss
  src/components/Button/style.scss
  src/components/DatePicker/style.scss
  src/components/Modal/style.scss
  src/components/Popover/index.tsx
  src/components/Popover/style.scss
  src/components/RangePicker/style.scss
  src/components/TimePicker/style.scss
  src/components/Tree/style.scss
  src/style/bootstrap-custom.scss
  src/style/bootstrap.scss
  src/style/variables.scss
  stories/Popover.stories.tsx
  stories/docs/Tree.mdx
Labels: bug, 3-Changed

#281 fix: button tooltip bug
  src/components/Button/style.scss
Labels: bug, 1-Review, 4-Approved

#280 fix: ui problems
  src/components/Button/style.scss
  src/components/DatePicker/style.scss
  src/components/Popover/index.tsx
  src/components/RangePicker/style.scss
  src/components/TimePicker/style.scss
Labels: bug

#285 fix: fix vlist error try to fetch data
  src/components/VirtualList/index.tsx
  src/interface.tsx
Labels: 4-Approved

#283 fix: dot-size
  src/components/Badge/style.scss
  src/components/UsageBar/style.scss
  src/style/variables.scss
Labels: 4-Approved

#286 fix: update rangepicker disabled
  src/components/RangePicker/index.tsx
  src/components/TimePicker/style.scss
  src/interface.tsx
  stories/RangePicker.stories.tsx
  stories/docs/RangePicker.mdx
Labels: bug, 1-Review

#289 fix: [XEOS-9999] fix tag z-index error
  src/components/Tabs/style.scss
Labels: 4-Approved

#290 fix: [XSOS-6275][XEOS-9999] fix datepicker code format error
  src/components/DatePicker/style.scss
  src/components/Tabs/style.scss
Labels: 1-Review

#291 fix: [XSOS-6398] fix tooltips center error
  src/components/Tooltip/index.tsx
  src/components/Tooltip/style.scss
  src/interface.tsx
Labels: 4-Approved

#292 refactor: replace color
  src/components/RangePicker/style.scss
  src/components/Tabs/style.scss
  src/components/TimePicker/style.scss
  src/style/bootstrap-custom.scss
  src/style/bootstrap.scss
  src/style/variables.scss
  src/style/variables.scss.d.ts
Labels: 4-Approved

#297 feat: Modal Component add onShow fun props
  src/components/Modal/index.tsx
Labels: 4-Approved

#296 fix: add formcheck input and label
  src/components/FormCheck/index.tsx
Labels: 4-Approved
