Repository xsky-fe/wizard-ui, pull requests merged in 2023-05, with the labels that each got.

#218 refactor: button
  src/components/Button/index.tsx
  src/components/Button/style.scss
  src/interface.tsx
  src/style/bootstrap-custom.scss
  stories/Button.stories.tsx
Labels: approve

#222 refactor: panel
  src/components/Panel/index.tsx
  src/style/bootstrap-custom.scss
Labels: approve

#229 add default button
  src/components/Button/index.tsx
  src/components/Button/style.scss
  src/interface.tsx
  src/style/bootstrap-custom.scss
  stories/Button.stories.tsx
Labels: changes

#227 refactor: tabs
  src/components/Tabs/index.tsx
  src/components/Tabs/style.scss
  src/style/bootstrap-custom.scss
Labels: approve

#220 refactor: popover
  src/components/Popover/index.tsx
  src/components/Popover/style.scss
  src/interface.tsx
  src/style/bootstrap-custom.scss
  stories/Popover.stories.tsx
Labels: approve

#232 modify input group component
  docs/src/components/Search/index.js
  stories/InputGroup.stories.tsx
Labels: approve

#231 refactor: button
  src/components/Button/index.tsx
  src/components/Button/style.scss
  src/interface.tsx
  stories/Button.stories.tsx
Labels: approve

#238 refactor: steps style
  src/components/Steps/index.tsx
  src/components/Steps/style.scss
  stories/Steps.stories.tsx
Labels: approve

#237 refactor: add checkbox and radio storybook
  stories/Checkbox.stories.tsx
  stories/InputGroup.stories.tsx
  stories/Radio.stories.tsx
Labels: approve

#234 fix tabs
  src/components/Tabs/index.tsx
  src/interface.tsx
Labels: approve

#241 refactor: adjust to virtualSelectBox
  src/components/VirtualSelectBox/index.tsx
  src/components/VirtualSelectBox/style.scss
Labels: approve

#248 fix: change dropdownbutton divider
  src/components/Dropdown/index.tsx
  src/components/DropdownButton/index.tsx
  src/components/SubMenu/index.tsx
  src/interface.tsx
  src/style/variables.scss
Labels: WIP
