Repository xsky-fe/wizard-ui, pull requests merged in 2023-07, with the labels that each got.

#271 fix: fix type define error
  package.json
  src/components/InputDropdown/index.tsx
  src/components/Tabs/index.tsx
  src/interface.tsx
Labels: bug, 1-Review, 4-Approved

#273 refactor: remove node-sass, add sass
  package.json
  src/components/Badge/style.scss
  src/components/Tabs/style.scss
  src/components/UsageBar/style.scss
  yarn.lock
Labels: 4-Approved

#272 fix: upgrade Tab and Alert Component
  package.json
  src/components/Alert/index.tsx
  src/components/Badge/style.scss
  src/components/Tabs/index.tsx
  src/components/Tabs/style.scss
  src/components/UsageBar/style.scss
  src/interface.tsx
  yarn.lock
Labels: 1-Review

#274 feat:usagebar
  src/components/UsageBar/index.tsx
  src/interface.tsx
  stories/UsageBar.stories.tsx
  stories/docs/UsageBar.mdx
Labels: 1-Review

#277 fix: button warning
  src/components/Button/index.tsx
Labels: bug, 1-Review

#279 feat: add false type in button tooltip
  src/components/Button/index.test.tsx
  src/components/Button/index.tsx
  src/components/DropdownButton/index.tsx
  src/interface.tsx
  stories/Button.stories.tsx
  stories/DropdownButton.stories.tsx
Labels: 4-Approved
